Feature/foodiv 93 michael
develcode-estagiarios-4/Develfood-Michael pull request #10
Opened 2022-05-27 19:34 UTC by Michael-Junges-Develcode

card 93 pronto, tratamento de erro do cadastro corrigido, validação do cep do yup corrigido

2022-05-27 20:07 UTC, gabriel-marques-develcode requested changes

2022-05-27 20:07 UTC, gabriel-marques-develcode commented on src/screens/StackNavigator/SignUpSuccess/index.tsx
> +    const [hidePassword, setHidePassword] = useState(false);
Avaliar a necessidade de declaração desse estado. Caso não seja, é bom remover.

2022-05-27 20:07 UTC, gabriel-marques-develcode commented on src/screens/StackNavigator/SignUpSuccess/index.tsx
> +    const [hideConfirmPassword, setHideConfirmPassword] = useState(false);
Avaliar a necessidade de declaração desse estado. Caso não seja, é bom remover.

2022-05-27 20:07 UTC, gabriel-marques-develcode commented on src/screens/StackNavigator/SignUpSuccess/index.tsx
> +    const [enableConfirmPassword, setEnableConfirmPassword] = useState(false);
Avaliar a necessidade de declaração desse estado. Caso não seja, é bom remover.

2022-05-27 20:07 UTC, gabriel-marques-develcode commented on src/screens/StackNavigator/SignUpSuccess/index.tsx
> +    const schema = yup.object().shape({
Avaliar a necessidade de declaração dessa constante. Caso não seja, é bom remover.

2022-05-28 02:25 UTC, Michael-Junges-Develcode commented
Removi as variáveis e estados não usados

2022-05-30 13:18 UTC, merged